name: multiple command

on:
  push:

jobs:
  commands:
    runs-on: ubuntu-latest

    steps:
      - name: store date
        run: date

      - name: show current folder
        run: pwd

      - name: show files
        run: ls -la